# Generated by Django 4.0.2 on 2022-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
