# Generated by Django 4.0.3 on 2022-04-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rider_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.point')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=128, unique=True)),
                ('max_participants', models.DecimalField(decimal_places=0, default=50, max_digits=2)),
                ('current_participants', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=4)),
                ('celebration_date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.point')),
            ],
        ),
    ]
