# Generated by Django 4.0.3 on 2022-04-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_point_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='next',
        ),
        migrations.RemoveField(
            model_name='route',
            name='point',
        ),
        migrations.AddField(
            model_name='point',
            name='position',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='point',
            name='route',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
    ]
