# Generated by Django 4.0.3 on 2022-04-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_point_next_remove_route_point_point_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='route',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.route'),
        ),
    ]
