# Generated by Django 4.0.3 on 2022-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_point_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='participants',
            field=models.ManyToManyField(related_name='rider_route', to='api.rider'),
        ),
    ]
