# Generated by Django 4.0.3 on 2022-04-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_route_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_point', to='api.route'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=128)),
                ('distance', models.FloatField()),
                ('duration', models.IntegerField(default=0)),
                ('avg_speed', models.FloatField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('rider', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
        ),
    ]
