# Generated by Django 4.0.3 on 2022-05-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_point_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='route_message', to='api.route')),
                ('writer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
        ),
    ]
