# Generated by Django 4.0.3 on 2022-05-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user', models.CharField(max_length=16)),
                ('rider', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rider_observer', to='api.rider')),
            ],
        ),
    ]
