# Generated by Django 4.0.3 on 2022-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_observer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='telegram_user',
        ),
        migrations.AddField(
            model_name='rider',
            name='last_x_coord',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_y_coord',
            field=models.FloatField(default=None, null=True),
        ),
    ]
