# Generated by Django 4.0.3 on 2022-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_horse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='years',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='horse',
            name='image',
            field=models.ImageField(upload_to='horse_images'),
        ),
    ]
