# Generated by Django 4.0.3 on 2022-05-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_years_horse_age_alter_horse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='image',
            field=models.ImageField(null=True, upload_to='horse_images'),
        ),
        migrations.AlterField(
            model_name='route',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
    ]
