# Generated by Django 4.0.3 on 2022-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_route_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='friends',
            field=models.ManyToManyField(related_name='rider_friend', to='api.rider'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='observers',
            field=models.ManyToManyField(related_name='rider_observer', to='api.rider'),
        ),
    ]
